[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Optional: local dev config if using Netlify CLI
#[dev]
#  command = "npm run dev"
#  port = 8888
#  publish = "dist"
